### ISSUE TITLE
support scoped name

### ISSUE THREAD

**Issue by ysmood** [dracupid/npm-up#3]
Such as `package.json` like below won't work.

```json
{
  "name": "test",
  "dependencies": {
    "@username/project-name": "1.0.0"
  }
}
```

This may help: https://docs.npmjs.com/getting-started/scoped-packages

**Comment by dracupid** [comment]
I'd like to fix this in the week.:smile:

However, it seems that scoped-packages are not supported on taobao npm mirror. Please notice this if you are using it.
For example
- [OK] http://registry.npmjs.org/-/package/@ysmood%2fmaterial-ui/dist-tags
- [OK] http://registry.cnpmjs.org/-/package/@ysmood%2fmaterial-ui/dist-tags
- [404] http://registry.npm.taobao.org/-/package/@ysmood%2fmaterial-ui/dist-tags

Npm install use a fallback to deal with this problem, I may use the same way to fix it.
```
npm info attempt registry request try #1 at 18:59:44
npm http request GET http://registry.npm.taobao.org/@ysmood%2fmaterial-ui
npm http 304 http://registry.npm.taobao.org/@ysmood%2fmaterial-ui
npm info addNameTag [ '@ysmood/material-ui', 'latest' ]
npm info retry fetch attempt 1 at 18:59:46
npm info attempt registry request try #1 at 18:59:46
npm http fetch GET http://registry.npmjs.org/@ysmood/material-ui/-/material-ui-0.8.1.tgz
npm http fetch 200 http://registry.npmjs.org/@ysmood/material-ui/-/material-ui-0.8.1.tgz
```

**Comment by ysmood** [comment]
Sure. Public support is enough.

**Comment by dracupid** [comment]
try v2.5.0

**Comment by ysmood** [comment]
Tried it, no problem, thanks!
