### ISSUE TITLE
Feature request: --ignore-exact flag

### ISSUE THREAD

**Issue by hash-bang** [dracupid/npm-up#4]
One feature I would find especially useful is to have a means to upgrade everything except exact semver references - e.g. `npm-up -wi --ignore-exact`.

For example if the semver of a package indicates a locked version such as `1.2.3` and `--ignore-exact` is specified that version is *not* upgraded along with anything with a valid range (e.g. `^1.2.3`, `1.2.x` etc.).

The reason behind this is if a version is kept-back because it hasn't been trailed yet, or the latest release has bugs, this allows other packages to be upgraded without having to specify exclusion rules.

**Comment by dracupid** [comment]
That's reasonable.  I will consider adding some new options for locked version.

**Comment by dracupid** [comment]
I prefer adding some "pre-defined package set" for `--exclude` and `--include`, such as LOCKED，to accomplish this feature. Is that OK?

**Comment by hash-bang** [comment]
That sounds a more elegant way of dealing with it yes.

Just for convenience can we have an alias to make it easier to use without typing the exclude variant each time? Something like `npm-up -wp` =~ `npm-up -w --exclude LOCKED` (where `-p`, preserve, translates to `--exclude LOCKED`). Similar to how your `-a` flag switches some other flags.

**Comment by dracupid** [comment]
The "elegant way" will make it a little more complex.  I tried to make as less change to the code as possible. So finally Just a new `--exclude-locked, or -p` option will be added.  I don't have much time to spend on this project recently.

**Comment by hash-bang** [comment]
Its working great!

Thanks for your help.
