### ISSUE TITLE
Crashes with latest NPM@7

### ISSUE THREAD

**Issue by hash-bang** [dracupid/npm-up#5]
For some reason the context + options don't get passed correctly when calling `npm.load()` with npm@7. This is probably because that function no longer accepts options to merge in with its own config.

This can be fixed by patching the npm.load() block to use a simple callback + set options using the setter.

In dist/npm-up.js this would be:

```javascript
  return npm.load(()=> { // While this could be run via promisify for some reason the context doesn't get passed so we have to use Callbacks
    var p, promise;
    Object.entries(npmOpt).forEach(([key, val]) => // Carry over all options after load
      npm.config.set(key, val)
    );
    // ... rest of code omitted ... //
```

I would file a PR with this patch but I don't know how to code in Coffee.

**Comment by dracupid** [comment]
I tried to fix it on 2.7.0. There is a big API change on npm@7, including load and install.

**Comment by hash-bang** [comment]
@dracupid, yeah it looks like they changed the pathing API.

I tried a few approaches but I'm not great with CoffeeScript, so it would still be pretty useless to you in a PR.

**Comment by dracupid** [comment]
Have you tried npm-up@2.7.0?

**Comment by hash-bang** [comment]
Ah sorry I didn't realise you had published a new version.

Yes its working, excellent! I do love this tool for managing upgrades.

Great work.
